// Conclave themes — verbatim from the ISFCC 2026 Brochure ("CONCLAVE THEMES").
// The Conclave invites participation, presentations, and papers across these
// thematic tracks (indicative, not limited to). Do not invent topics.

export const TRACKS_NOTE =
  "The Conclave invites participation, presentations, and papers across the following thematic tracks (indicative, not limited to).";

export const TRACKS = [
  {
    title: "Smart & Sustainable Urban Infrastructure",
    topics: [
      "Smart-city roadmap: policy reforms, planning, infrastructure & investments",
      "Sustainable urban planning and resilient infrastructure",
      "Public–Private Partnerships (PPP) for urban development",
      "Smart villages and rural transformation",
      "Green buildings, net-zero buildings & sustainable architecture",
      "Smart construction technologies and Building Information Modeling (BIM)",
      "Real estate: commercial, residential, institutional & technology-enabled developments",
      "Urban infrastructure asset management",
      "Smart campuses and integrated urban ecosystems",
      "Digital twins for infrastructure planning",
    ],
  },
  {
    title: "Digital Governance & Citizen-Centric Services",
    topics: [
      "E-governance and digital public services",
      "Digital transformation for socio-economic development",
      "Smart governance and policy innovation",
      "Cybersecurity, privacy and digital trust",
      "Smart policing and public safety",
      "Smart traffic management systems",
      "Citizen-centric public service innovation",
      "Digital inclusion and digital public infrastructure",
      "Data governance and digital policy",
      "AI-enabled public administration",
    ],
  },
  {
    title: "AI, IoT & Emerging Technologies for Cities",
    topics: [
      "Artificial Intelligence for smart cities",
      "Human–AI collaboration and intelligent systems",
      "Internet of Things (IoT) and smart urban applications",
      "Machine Learning and Deep Learning",
      "Generative AI and Responsible AI",
      "Robotics and intelligent automation",
      "Edge computing and cloud technologies",
      "Digital twins and cyber-physical systems",
      "Smart sensors and intelligent monitoring",
      "Predictive analytics and data-driven decision-making",
    ],
  },
  {
    title: "Climate Resilience, Sustainability & Environmental Management",
    topics: [
      "Climate resilience and adaptation strategies",
      "Sustainable urban development",
      "Environmental sustainability and conservation",
      "Circular economy practices",
      "Waste management and recycling technologies",
      "Clean rivers and water conservation",
      "Forest and biodiversity protection",
      "Air quality monitoring and pollution control",
      "Carbon neutrality and ESG practices",
      "Sustainable Development Goals (SDGs)",
    ],
  },
  {
    title: "Smart Mobility & Intelligent Transportation",
    topics: [
      "Smart transportation systems",
      "Intelligent traffic management",
      "Sustainable urban mobility",
      "Metro, monorail and mass rapid transit",
      "Electric and autonomous vehicles",
      "Urban air mobility and airport development",
      "Civil aviation innovation",
      "Air cargo and logistics",
      "Green logistics and freight transportation",
      "Smart warehousing and last-mile delivery",
    ],
  },
  {
    title: "Urban Innovation, Entrepreneurship & Startup Ecosystems",
    topics: [
      "Startup ecosystems and innovation hubs",
      "MSME development and digital transformation",
      "Technology commercialization",
      "Entrepreneurship and business incubation",
      "Invest in Uttarakhand",
      "Smart manufacturing and Industry 5.0",
      "Innovation management",
      "Rural entrepreneurship",
      "Women entrepreneurship",
      "Social entrepreneurship",
    ],
  },
  {
    title: "Research, Policy & Capacity Building for Future Cities",
    topics: [
      "Sustainable urban policy frameworks",
      "Capacity building and knowledge dissemination",
      "Research methodologies and innovation",
      "Student innovation initiatives",
      "Smart and clean cities initiatives",
      "Industry-oriented research",
      "Research paper presentations",
      "Technology transfer and commercialization",
      "Future city governance",
      "Policy implementation and impact assessment",
    ],
  },
  {
    title: "Industry–Academia–Government Collaboration",
    topics: [
      "Industry–academia partnerships",
      "Government–industry collaboration",
      "International collaboration and diplomacy",
      "India–Africa economic partnerships",
      "Foreign trade and EXIM policy",
      "Free Trade Agreements (FTAs)",
      "Public–Private Partnerships (PPP)",
      "Joint ventures and technology transfer",
      "Research and innovation collaborations",
      "Smart governance through collaborative ecosystems",
    ],
  },
  {
    title: "Civil Engineering, Water Resources & Environmental Infrastructure",
    topics: [
      "Sustainable civil engineering practices",
      "Smart roads, highways and bridge engineering",
      "Water resources engineering and integrated water management",
      "Smart water supply and distribution systems",
      "Wastewater treatment and sewage management",
      "Stormwater drainage and flood management",
      "River rejuvenation and watershed management",
      "Urban sanitation systems",
      "Construction materials and advanced infrastructure technologies",
      "Disaster-resilient infrastructure",
    ],
  },
  {
    title: "Computer Science, Information Technology & Cybersecurity",
    topics: [
      "Smart computing technologies",
      "Cloud computing and distributed systems",
      "Big data analytics",
      "Blockchain technologies",
      "Cybersecurity and digital asset protection",
      "Information security and cyber resilience",
      "AI-driven cybersecurity",
      "Secure digital infrastructure",
      "Software engineering for smart cities",
      "Digital innovation and intelligent applications",
    ],
  },
  {
    title: "Electrical, Electronics & Renewable Energy Systems",
    topics: [
      "Smart grids and intelligent power systems",
      "Renewable energy: solar, wind, hydro and green hydrogen",
      "Energy storage technologies",
      "Power generation, transmission and distribution",
      "Electric mobility infrastructure",
      "Smart metering and energy management",
      "Industrial electronics and embedded systems",
      "Energy-efficient technologies",
      "Sustainable electrical infrastructure",
      "Intelligent energy systems",
    ],
  },
  {
    title: "Logistics, Supply Chain & Operations Management",
    topics: [
      "Digital supply chains",
      "Sustainable supply chain management",
      "Green logistics and circular supply chains",
      "AI-enabled supply chain management",
      "Warehouse automation and smart logistics",
      "Procurement and inventory optimization",
      "Supply chain resilience and risk management",
      "Reverse logistics and waste recovery",
      "Cold chain logistics",
      "Supply chain analytics",
    ],
  },
  {
    title: "Business, Management & Sustainable Development",
    topics: [
      "Strategic management",
      "Sustainable business models",
      "Sustainable management practices",
      "Business analytics",
      "Innovation and technology management",
      "Project and operations management",
      "Digital business transformation",
      "Knowledge management",
      "Risk and resilience management",
      "Corporate governance and ESG",
    ],
  },
  {
    title: "Marketing, Consumer Behaviour & Business Analytics",
    topics: [
      "AI in marketing",
      "Human–AI collaboration in marketing",
      "Marketing analytics",
      "Consumer analytics",
      "Consumer behaviour in the digital economy",
      "Customer experience and customer loyalty",
      "AI-enabled personalization",
      "Digital marketing and social media analytics",
      "Retail analytics and e-commerce",
      "Green marketing and sustainable consumption",
    ],
  },
  {
    title: "Finance, FinTech & Economic Development",
    topics: [
      "Financial technologies (FinTech)",
      "Sustainable FinTech",
      "Green finance",
      "Digital banking and digital payments",
      "Financial inclusion",
      "ESG investing",
      "AI in finance",
      "Financial analytics",
      "Blockchain in financial systems",
      "Sustainable investment strategies",
    ],
  },
  {
    title: "Human Resource Management & Organizational Analytics",
    topics: [
      "Human resource analytics",
      "People analytics",
      "AI in human resource management",
      "Talent management",
      "Workforce transformation",
      "Employee experience and engagement",
      "Leadership and organizational behaviour",
      "Future of work",
      "Learning and development",
      "Diversity, equity and inclusion",
    ],
  },
  {
    title: "Healthcare, HealthTech & Smart Wellness",
    topics: [
      "AI in healthcare",
      "Smart hospitals",
      "Digital health and telemedicine",
      "Medical IoT applications",
      "Healthcare analytics",
      "Public health systems",
      "Healthcare infrastructure",
      "Healthcare supply chains",
      "Health policy and universal healthcare",
      "Wellness technologies",
    ],
  },
  {
    title: "Tourism, Hospitality & Smart Destinations",
    topics: [
      "Smart tourism",
      "Sustainable tourism",
      "Eco-tourism and rural tourism",
      "Smart hospitality systems",
      "Tourism analytics",
      "Aviation and tourism development",
      "Destination management",
      "Cultural and heritage tourism",
      "Hospitality innovation",
      "Tourism investment",
    ],
  },
] as const;

export const SECTOR_FOCUS = [
  "Smart Cities",
  "Healthcare & Wellness",
  "Waste Management",
  "Real Estate",
  "Power & Renewable Energy",
  "Urban Mobility",
  "Civil Aviation",
  "Information Technology",
  "Tourism",
  "Diplomatic Conclave & International Citizenship",
] as const;
